apiVersion: v1
kind: PersistentVolume
metadata:
  name: free5gc-pv-mongo
  labels:
    project: free5gc
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  nfs:
    server: 192.168.10.10  # kpt-set: ${nfs-server}
    path: /var/nfs/general/mongo
    readOnly: false
