apiVersion: v1
data:
  udrcfg.yaml: |
    info:
      version: 1.1.0
      description: UDR initial local configuration

    configuration:
      sbi:
        scheme: http
        registerIPv4: free5gc-free5gc-udr-service # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: 80
        tls:
          key: ./cert/udr.key
          pem: ./cert/udr.pem
      dbConnectorType: mongodb
      mongodb:
        name: free5gc
        url: mongodb://mongodb:27017

      nrfUri: http://nrf-nnrf:8000
      nrfCertPem: cert/nrf.pem

    logger:
      enable: true
      level: info
      reportCaller: false
kind: ConfigMap
metadata:
  labels:
    app: free5gc
  name: free5gc-free5gc-udr-configmap
  namespace: 5gcore  # kpt-set: ${namespace}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: free5gc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: free5gc-udr
    app.kubernetes.io/version: latest
    helm.sh/chart: free5gc-udr-0.2.7
    nf: udr
    project: free5gc
  name: free5gc-free5gc-udr-service
  namespace: 5gcore  # kpt-set: ${namespace}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/instance: free5gc
    app.kubernetes.io/name: free5gc-udr
    nf: udr
    project: free5gc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: free5gc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: free5gc-udr
    app.kubernetes.io/version: latest
    helm.sh/chart: free5gc-udr-0.2.7
    nf: udr
    project: free5gc
  name: free5gc-free5gc-udr-udr
  namespace: 5gcore  # kpt-set: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: free5gc
      app.kubernetes.io/name: free5gc-udr
      nf: udr
      project: free5gc
  template:
    metadata:
      annotations:
        checksum/config: e4bcd3c68bd3337236dd55de459564493dda9170aca51fa6be0549e7688a33c6
      labels:
        app.kubernetes.io/instance: free5gc
        app.kubernetes.io/name: free5gc-udr
        nf: udr
        project: free5gc
    spec:
      affinity: {}
      containers:
        - args:
            - -c
            - ./config/udrcfg.yaml
          command:
            - ./udr
          env:
            - name: DB_URI
              value: mongodb://mongodb/free5gc
            - name: GIN_MODE
              value: release
          image: free5gc/udr:v4.0.1  # kpt-set: ${image-udr}
          imagePullPolicy: Always
          name: udr
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext: {}
          volumeMounts:
            - mountPath: /free5gc/config/
              name: free5gc-free5gc-udr-volume
            - mountPath: /free5gc/config/TLS
              name: free5gc-free5gc-udr-empty-volume
            - mountPath: /free5gc/cert
              name: free5gc-free5gc-udr-cert-pvc
      dnsPolicy: ClusterFirst
      imagePullSecrets: []
      initContainers:
        - command:
            - sh
            - -c
            - set -x; for dependency in $DEPENDENCIES; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $dependency) -ne 200 ]; do echo waiting for dependencies; sleep 1; done; done;
          env:
            - name: DEPENDENCIES
              value: http://nrf-nnrf:8000
          image: curlimages/curl:8.7.1
          name: wait-nrf
      nodeSelector: {}
      restartPolicy: Always
      securityContext: {}
      tolerations: []
      volumes:
        - name: free5gc-free5gc-udr-volume
          projected:
            sources:
              - configMap:
                  name: free5gc-free5gc-udr-configmap
        - emptyDir: {}
          name: free5gc-free5gc-udr-empty-volume
        - name: free5gc-free5gc-udr-cert-pvc
          persistentVolumeClaim:
            claimName: cert-pvc
