apiVersion: v1
data:
  ausfcfg.yaml: |
    info:
      version: 1.0.3
      description: AUSF initial local configuration

    configuration:
      serviceNameList:
        - nausf-auth

      sbi:
        scheme: http
        registerIPv4: free5gc-free5gc-ausf-service # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: 80
        tls:
          key: ./cert/ausf.key
          pem: ./cert/ausf.pem

      nrfUri: http://nrf-nnrf:8000
      nrfCertPem: ./cert/nrf.pem # NRF Certificate
      plmnSupportList:
        - mcc: 208
          mnc: 93
        - mcc: 123
          mnc: 45
      groupId: ausfGroup001
      eapAkaSupiImsiPrefix: false

    logger:
      enable: true
      level: info
      reportCaller: false
kind: ConfigMap
metadata:
  labels:
    app: free5gc
  name: free5gc-free5gc-ausf-configmap
  namespace: 5gcore  # kpt-set: ${namespace}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: free5gc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: free5gc-ausf
    app.kubernetes.io/version: latest
    helm.sh/chart: free5gc-ausf-0.2.7
    nf: ausf
    project: free5gc
  name: free5gc-free5gc-ausf-service
  namespace: 5gcore  # kpt-set: ${namespace}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/instance: free5gc
    app.kubernetes.io/name: free5gc-ausf
    nf: ausf
    project: free5gc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: free5gc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: free5gc-ausf
    app.kubernetes.io/version: latest
    helm.sh/chart: free5gc-ausf-0.2.7
    nf: ausf
    project: free5gc
  name: free5gc-free5gc-ausf-ausf
  namespace: 5gcore  # kpt-set: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: free5gc
      app.kubernetes.io/name: free5gc-ausf
      nf: ausf
      project: free5gc
  template:
    metadata:
      annotations:
        checksum/config: eacbc3e916e18a1525c524b3e74f2ecad6cc7e5a1d5370376e63fa9ea37db44f
      labels:
        app.kubernetes.io/instance: free5gc
        app.kubernetes.io/name: free5gc-ausf
        nf: ausf
        project: free5gc
    spec:
      affinity: {}
      containers:
        - args:
            - -c
            - ./config/ausfcfg.yaml
          command:
            - ./ausf
          env:
            - name: GIN_MODE
              value: release
          image: free5gc/ausf:v4.0.1  # kpt-set: ${image-ausf}
          imagePullPolicy: Always
          name: ausf
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext: {}
          volumeMounts:
            - mountPath: /free5gc/config/
              name: free5gc-free5gc-ausf-volume
            - mountPath: /free5gc/config/TLS
              name: free5gc-free5gc-ausf-empty-volume
            - mountPath: /free5gc/cert
              name: free5gc-free5gc-ausf-cert-pvc
      dnsPolicy: ClusterFirst
      imagePullSecrets: []
      initContainers:
        - command:
            - sh
            - -c
            - set -x; for dependency in $DEPENDENCIES; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $dependency) -ne 200 ]; do echo waiting for dependencies; sleep 1; done; done;
          env:
            - name: DEPENDENCIES
              value: http://nrf-nnrf:8000
          image: curlimages/curl:8.7.1
          name: wait-nrf
      nodeSelector: {}
      restartPolicy: Always
      securityContext: {}
      tolerations: []
      volumes:
        - name: free5gc-free5gc-ausf-volume
          projected:
            sources:
              - configMap:
                  name: free5gc-free5gc-ausf-configmap
        - emptyDir: {}
          name: free5gc-free5gc-ausf-empty-volume
        - name: free5gc-free5gc-ausf-cert-pvc
          persistentVolumeClaim:
            claimName: cert-pvc
