apiVersion: v1
data:
  pcfcfg.yaml: |
    info:
      version: 1.0.2
      description: PCF initial local configuration

    configuration:
      serviceList:
        - serviceName: npcf-am-policy-control
        - serviceName: npcf-smpolicycontrol
          suppFeat: 3fff
        - serviceName: npcf-bdtpolicycontrol
        - serviceName: npcf-policyauthorization
          suppFeat: 3
        - serviceName: npcf-eventexposure
        - serviceName: npcf-ue-policy-control

      sbi:
        scheme: http
        registerIPv4: free5gc-free5gc-pcf-service # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: 80
        tls:
          key: ./cert/pcf.key
          pem: ./cert/pcf.pem

      mongodb:       # the mongodb connected by this PCF
        name: free5gc                  # name of the mongodb
        url: mongodb://mongodb:27017 # a valid URL of the mongodb

      nrfUri: http://nrf-nnrf:8000
      nrfCertPem: cert/nrf.pem
      pcfName: PCF
      timeFormat: 2019-01-02 15:04:05
      defaultBdtRefId: BdtPolicyId-
      locality: area1

    logger:
      enable: true
      level: info
      reportCaller: false
kind: ConfigMap
metadata:
  labels:
    app: free5gc
  name: free5gc-free5gc-pcf-configmap
  namespace: 5gcore  # kpt-set: ${namespace}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: free5gc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: free5gc-pcf
    app.kubernetes.io/version: latest
    helm.sh/chart: free5gc-pcf-0.2.7
    nf: pcf
    project: free5gc
  name: free5gc-free5gc-pcf-service
  namespace: 5gcore  # kpt-set: ${namespace}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/instance: free5gc
    app.kubernetes.io/name: free5gc-pcf
    nf: pcf
    project: free5gc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: free5gc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: free5gc-pcf
    app.kubernetes.io/version: latest
    helm.sh/chart: free5gc-pcf-0.2.7
    nf: pcf
    project: free5gc
  name: free5gc-free5gc-pcf-pcf
  namespace: 5gcore  # kpt-set: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: free5gc
      app.kubernetes.io/name: free5gc-pcf
      nf: pcf
      project: free5gc
  template:
    metadata:
      annotations:
        checksum/config: b476a731ae48f546175b087b61d9ffd92cb5a21f90bf83f4c83a517efd15d5bb
      labels:
        app.kubernetes.io/instance: free5gc
        app.kubernetes.io/name: free5gc-pcf
        nf: pcf
        project: free5gc
    spec:
      affinity: {}
      containers:
        - args:
            - -c
            - ./config/pcfcfg.yaml
          command:
            - ./pcf
          env:
            - name: GIN_MODE
              value: release
          image: free5gc/pcf:v4.0.1  # kpt-set: ${image-pcf}
          imagePullPolicy: Always
          name: pcf
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext: {}
          volumeMounts:
            - mountPath: /free5gc/config/
              name: free5gc-free5gc-pcf-volume
            - mountPath: /free5gc/config/TLS
              name: free5gc-free5gc-pcf-empty-volume
            - mountPath: /free5gc/cert
              name: free5gc-free5gc-pcf-cert-pvc
      dnsPolicy: ClusterFirst
      imagePullSecrets: []
      initContainers:
        - command:
            - sh
            - -c
            - set -x; for dependency in $DEPENDENCIES; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $dependency) -ne 200 ]; do echo waiting for dependencies; sleep 1; done; done;
          env:
            - name: DEPENDENCIES
              value: http://nrf-nnrf:8000
          image: curlimages/curl:8.7.1
          name: wait-nrf
      nodeSelector: {}
      restartPolicy: Always
      securityContext: {}
      tolerations: []
      volumes:
        - name: free5gc-free5gc-pcf-volume
          projected:
            sources:
              - configMap:
                  name: free5gc-free5gc-pcf-configmap
        - emptyDir: {}
          name: free5gc-free5gc-pcf-empty-volume
        - name: free5gc-free5gc-pcf-cert-pvc
          persistentVolumeClaim:
            claimName: cert-pvc
