apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  namespace: upf-migrate-system
  image-manager: kiepdoden123/upf-manager:hybrid-host-device-v3
  aws-region: us-east-2
  nrf-address: "192.168.10.10:30348"
  5gcore-namespace: "5gcore"
  sdn-controller-address: "192.168.1.10:8000"
  # Host:port UPF pod dùng để gọi gRPC ngược lại manager (LoadBalancer IP:7000 của Service trong package này)
  grpc-host: "192.168.10.10:7000"
