apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    karmada.io/bootstrapping: app-defaults
  name: karmada-aggregated-apiserver
  namespace: karmada-system  # kpt-set: ${namespace}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      apiserver: 'true'
      app: karmada-aggregated-apiserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        apiserver: 'true'
        app: karmada-aggregated-apiserver
      name: karmada-aggregated-apiserver
      namespace: karmada-system  # kpt-set: ${namespace}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - karmada-aggregated-apiserver
            topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: false
      containers:
      - command:
        - /bin/karmada-aggregated-apiserver
        - --kubeconfig=/etc/karmada/config/karmada.config
        - --authentication-kubeconfig=/etc/karmada/config/karmada.config
        - --authorization-kubeconfig=/etc/karmada/config/karmada.config
        - --etcd-servers=https://etcd-0.etcd.karmada-system.svc.cluster.local:2379
        - --etcd-cafile=/etc/karmada/pki/etcd-ca.crt
        - --etcd-certfile=/etc/karmada/pki/etcd-client.crt
        - --etcd-keyfile=/etc/karmada/pki/etcd-client.key
        - --tls-cert-file=/etc/karmada/pki/karmada.crt
        - --tls-private-key-file=/etc/karmada/pki/karmada.key
        - --tls-min-version=VersionTLS13
        - --audit-log-path=-
        - --audit-log-maxage=0
        - --audit-log-maxbackup=0
        - --bind-address=$(POD_IP)
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: docker.io/karmada/karmada-aggregated-apiserver:v1.17.1  # kpt-set: ${image-karmada-aggregated-apiserver}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: karmada-aggregated-apiserver
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 1
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 15
        resources:
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/karmada/config
          name: karmada-config
          readOnly: true
        - mountPath: /etc/karmada/pki
          name: karmada-cert
          readOnly: true
      dnsPolicy: ClusterFirst
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: karmada-config
        secret:
          defaultMode: 420
          secretName: karmada-aggregated-apiserver-config
      - name: karmada-cert
        secret:
          defaultMode: 420
          secretName: karmada-cert
