apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    karmada.io/bootstrapping: app-defaults
  name: karmada-webhook
  namespace: karmada-system  # kpt-set: ${namespace}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: karmada-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: karmada-webhook
      name: karmada-webhook
      namespace: karmada-system  # kpt-set: ${namespace}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - karmada-webhook
            topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: false
      containers:
      - command:
        - /bin/karmada-webhook
        - --kubeconfig=/etc/karmada/config/karmada.config
        - --bind-address=$(POD_IP)
        - --metrics-bind-address=$(POD_IP):8080
        - --health-probe-bind-address=$(POD_IP):8000
        - --secure-port=8443
        - --cert-dir=/var/serving-cert
        - --v=4
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: docker.io/karmada/karmada-webhook:v1.17.1  # kpt-set: ${image-karmada-webhook}
        imagePullPolicy: IfNotPresent
        name: karmada-webhook
        ports:
        - containerPort: 8443
          name: webhook
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8443
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/karmada/config
          name: karmada-config
          readOnly: true
        - mountPath: /var/serving-cert
          name: karmada-webhook-cert
          readOnly: true
      dnsPolicy: ClusterFirst
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: karmada-config
        secret:
          defaultMode: 420
          secretName: karmada-webhook-config
      - name: karmada-webhook-cert
        secret:
          defaultMode: 420
          secretName: karmada-webhook-cert
