apiVersion: v1
kind: Service
metadata:
  labels:
    karmada.io/bootstrapping: service-defaults
  name: kube-controller-manager
  namespace: karmada-system  # kpt-set: ${namespace}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: server
    port: 10257
    protocol: TCP
    targetPort: 10257
  selector:
    app: kube-controller-manager
  sessionAffinity: None
  type: ClusterIP
