apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    karmada.io/bootstrapping: app-defaults
  name: etcd
  namespace: karmada-system  # kpt-set: ${namespace}
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: etcd
  serviceName: etcd
  template:
    metadata:
      labels:
        app: etcd
      name: etcd
      namespace: karmada-system  # kpt-set: ${namespace}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - etcd
              topologyKey: kubernetes.io/hostname
            weight: 100
      automountServiceAccountToken: false
      containers:
      - command:
        - /usr/local/bin/etcd
        - --name=$(POD_NAME)
        - --listen-peer-urls=http://$(POD_IP):2380
        - --listen-client-urls=https://$(POD_IP):2379,http://127.0.0.1:2379
        - --advertise-client-urls=https://$(POD_NAME).etcd.karmada-system.svc.cluster.local:2379
        - --initial-cluster=etcd-0=http://etcd-0.etcd.karmada-system.svc.cluster.local:2380
        - --initial-cluster-state=new
        - --client-cert-auth=true
        - --cert-file=/etc/karmada/pki/etcd-server.crt
        - --key-file=/etc/karmada/pki/etcd-server.key
        - --trusted-ca-file=/etc/karmada/pki/etcd-ca.crt
        - --data-dir=/var/lib/karmada-etcd
        - --cipher-suites=TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - --initial-cluster-token=etcd-cluster
        - --initial-advertise-peer-urls=http://$(POD_IP):2380
        - --peer-client-cert-auth=false
        - --peer-trusted-ca-file=/etc/karmada/pki/etcd-ca.crt
        - --peer-key-file=/etc/karmada/pki/etcd-server.key
        - --peer-cert-file=/etc/karmada/pki/etcd-server.crt
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: registry.k8s.io/etcd:3.6.6-0  # kpt-set: ${image-etcd}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - etcdctl endpoint health --endpoints http://127.0.0.1:2379
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        name: etcd
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/karmada-etcd
          name: etcd-data
        - mountPath: /etc/etcd
          name: etcd-config
        - mountPath: /etc/karmada/pki
          name: etcd-cert
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        karmada.io/etcd: ''
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: etcd-cert
        secret:
          defaultMode: 420
          secretName: etcd-cert
      - emptyDir: {}
        name: etcd-config
      - hostPath:
          path: /var/lib/karmada-etcd  # kpt-set: ${etcd-hostpath}
          type: DirectoryOrCreate
        name: etcd-data
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
