apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  # Namespace of AMF, shared with package free5gc-5gcore-others
  namespace: 5gcore
  # Container image
  image-amf: free5gc/amf:v4.0.0
